/* C application - generated by Brief */
/* Target: Bare-metal ARM (Cortex-A) */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* @ link: hw_control -> 0x8000A000 */
#define HW_CONTROL_ADDR 0x8000A000
#define HW_CONTROL (*(volatile uint32_t *)HW_CONTROL_ADDR)

/* @ link: hw_status -> 0x8000A004 */
#define HW_STATUS_ADDR 0x8000A004
#define HW_STATUS (*(volatile uint32_t *)HW_STATUS_ADDR)

/* @ link: hw_opcode -> 0x8000A008 */
#define HW_OPCODE_ADDR 0x8000A008
#define HW_OPCODE (*(volatile uint32_t *)HW_OPCODE_ADDR)

typedef struct {
    uint32_t control;
    uint32_t status;
    uint32_t opcode;
    uint32_t token_count;
    bool modelLoaded;
    uint32_t kernel_state;
} State;

static State state_instance;
static State *state = &state_instance;

void state_init(void) {
    state->control = 0;
    state->status = 0;
    state->opcode = 0;
    state->token_count = 0;
    state->modelLoaded = false;
    state->kernel_state = 0;
}

bool flush_cache(void) {
    /* pre: Bool(true) */
    /* asm: dsb sy */
    __asm__ __volatile__(
        "dsb sy \n"
    );
    /* transaction complete */
    /* post: Bool(true) */
    return true;
}

bool load_model(void) {
    /* pre: Eq(Identifier("modelLoaded"), Bool(false)) */
    state->modelLoaded = true;
    state->kernel_state = 1;
    /* transaction complete */
    /* post: Eq(Identifier("modelLoaded"), Bool(true)) */
    return true;
}

bool idle(void) {
    /* pre: Eq(Identifier("kernel_state"), Integer(0)) */
    state->kernel_state = 0;
    /* transaction complete */
    /* post: Eq(Identifier("kernel_state"), Integer(0)) */
    return true;
}

bool ready(void) {
    /* pre: And(Eq(Identifier("kernel_state"), Integer(1)), Eq(Identifier("modelLoaded"), Bool(true))) */
    state->kernel_state = 2;
    /* transaction complete */
    /* post: Eq(Identifier("kernel_state"), Integer(2)) */
    return true;
}

bool waiting(void) {
    /* pre: Eq(Identifier("kernel_state"), Integer(2)) */
    state->kernel_state = 2;
    /* transaction complete */
    /* post: Eq(Identifier("kernel_state"), Integer(2)) */
    return true;
}

void brief_init(void) {
    // Static allocation for bare-metal
    state_init();
}

int main(void) {
    brief_init();
    return 0;
}
